storage: file # Default storage methods: file (stored in a .json file), sql (stored in an SQL server)

################################################
# ONLY USE IF YOU ARE USING SQL STORAGE METHOD #
################################################
ip: localhost
port: 3306
database: locks
username: root
password: ''